server:
  port: 8089
spring:
  application:
    name: SB-ADMIN
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: cloud   
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}